apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: http-port
      protocol: TCP
      port: 9002
      targetPort: 8080
