apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: task2-deployment
  labels:
    app: task2
spec:
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
        app: task2
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: vol
          mountPath: /logs
      volumes:
      - name: vol
        hostPath:
          path: /var/log
