apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-canary-deploy
  labels:
    app: canary-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-nginx
  template:
    metadata:
      labels:
        app: canary-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-index
          mountPath: /usr/share/nginx/html
      volumes:
        - name: my-index
          configMap:
            name: canary-configmap
            items:
              - key: index.html
                path: index.html

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: canary-configmap
data:
  index.html: |
    <html>
    <head>
      <title>canary nginx</title>
    </head>
    <body>
      <h1>It is canary nginx!</h1>
      <p>WOW!!! SO canary!!</p>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
spec:
  selector:
    app: canary-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
